version: '3.1'
#推荐内存2GB，edge版为开发版分支尝试nginx+php-fpm+mysql
services:
    sspanel:
        image: "baiyuetribe/sspanel:edge"
        #build : .
        restart: always
        container_name: sspanel         
        networks:
            - frontend
            - backend
        ports:
          - 666:80 
        volumes:
          - /opt/sspanel/code:/var/www/html 

    mysql:
        image: "mysql:8.0.17"
        restart: always
        environment:
          TZ: 'Asia/Shanghai'
          MYSQL_DATABASE: sspanel
          MYSQL_ROOT_PASSWORD: sspanel
        volumes:
          - /opt/sspanel/mysql:/var/lib/mysql
          - /opt/sspanel/code/sql/glzjin_all.sql:/docker-entrypoint-initdb.d/sspanel.sql
        command: ['mysqld', '--character-set-server=utf8']          
        networks:
            - backend
        depends_on:
          - sspanel                       
networks:
    frontend:
    backend:
